layer_with_traj: true
publish_keypoints: true
world_frame: "map"

extractor:
  verbose: true
  radius_feature: 15
  n_div: 10
  radius_local_extremum: 2
matcher:
  verbose: false
  max_corr_distance: 0.7
  k_dist: 0.9
  n_max_ransac: 1000000
  max_ransac_valid: 0.97
  o3d_visualize: false
  voc_file: "/workspaces/voxgraph_melodic_ws/src/freeture_matcher/config/freetures_voc.yml.gz"
  train_voc: false
  use_dbow: false
  min_local_fitness: 0
